name: Build Android

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v26.6.27)'
        required: true
        type: string

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Build Android Library
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_LATEST_HOME }}
        run: python3 build/main.py android

      - name: Rename artifacts
        run: |
          VER=${{ inputs.version }}

          mv libXray.aar "libXray-${VER}.aar"
          mv libXray-sources.jar "libXray-sources-${VER}.jar"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libXray-android-${{ inputs.version }}
          path: |
            libXray-*.aar
            libXray-sources*.jar
